### ISSUE TITLE
copier can't find repository 

### ISSUE THREAD

**Issue by pharmlovex** [kenibrewer/nf-modules-template#2]
When I ran the command below as instructed,
```bash
copier gh:nf-core/nf-modules-template ./my-new-modules-library
```
I got an error: 
`Unknown sub-comand 'gh:nf-core/nf-modules-template'`

I think this is expected because copier subcommand was not included. 

Therefore I tried
```bash
copier copy gh:nf-core/nf-modules-template ./my-new-modules-library
```
I got error:
`fatal: repository 'https://github.com/nf-core/nf-modules-template.git/' not found`

**Comment by kenibrewer** [comment]
Hi @pharmlovex . This repo has been migrated to `nf-core/modules-template`. So the correct command is 

```
copier copy gh:nf-core/modules-template ./my-new-modules-library
```

I corrected the instructions in the repo here and added an archive/migrate notice.
